GRANT SELECT ON ADM.THONGBAO TO PUBLIC;

SHOW CON_NAME;
/

BEGIN
    SA_SYSDBA.DROP_POLICY(
    POLICY_NAME  => 'P_THONGBAO');
END;
/

BEGIN SA_SYSDBA.CREATE_POLICY(
    POLICY_NAME  => 'P_THONGBAO',
    COLUMN_NAME  => 'DATA_LABEL'
); END;
/

GRANT P_THONGBAO_DBA TO ADMIN_OLS;
/
EXEC SA_SYSDBA.ENABLE_POLICY('P_THONGBAO') 


--CONNECT LAI

--label tag = (level value*100)+sum(compartment value*10)+sum(group value*1)

BEGIN
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',600, 'TKH', 'TRUONG KHOA');
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',500, 'TDV', 'TRUONG DON VI');
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',400, 'GV',  'GIANG VIEN');
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',300, 'GVU', 'GIAO VU');
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',200, 'NV',  'NHAN VIEN');
    SA_COMPONENTS.CREATE_LEVEL('P_THONGBAO',100, 'SV',  'SINH VIEN');

    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 10, 'HTTT','HE THONG THONG TIN');
    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 20, 'CNPM', 'CONG NGHE PHAN MEM');
    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 30, 'KHMT', 'KHOA HOC MAY TINH');
    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 40, 'CNTT', 'CONG NGHE TRI THUC');
    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 50, 'TGMT', 'THI GIAC MAY TINH');
    SA_COMPONENTS.CREATE_COMPARTMENT('P_THONGBAO', 60, 'MMT', 'MANG MAY TINH VA VIEN THONG');


    SA_COMPONENTS.CREATE_GROUP('P_THONGBAO', 700, 'CS1', 'CO SO 1', NULL);
    SA_COMPONENTS.CREATE_GROUP('P_THONGBAO', 800, 'CS2', 'CO SO 2', NULL);
    
END;



/
BEGIN
 --a) USER LB: TKH:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '63600','TKH:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
    
    
-- b) USER LB: 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '52800', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '52900', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS2');

    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '51600', 'TDV:HTTT:CS1,CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '51520', 'TDV:CNPM:CS1,CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '50900', 'TDV:CNPM:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '51400', 'TDV:MMT:CS2');
-- f) 
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '51000', 'TDV:KHMT:CS1');
    
    
-- c)
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '33600', 'GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '31900', 'GVU:KHMT,CNTT,TGMT:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '32000', 'GVU:TGMT:CS1,CS2');

-- d)
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '53600', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
-- e)
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '10800', 'SV:HTTT:CS1');
-- g)
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '51800', 'TDV:KHMT:CS1,CS2');
    
-- h1) CAC GIANG VIEN DOC DUOC HET THONG BAO CUA 2 CO SO KHONG QUAN TRONG BO MON
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '41500', 'GV::CS1,CS2');

-- h2) NHAN VIEN CO SO 1 DOC DUOC HET THONG BAO CUA CO SO MINH LAM VIEC KHONG QUAN TRONG BO MON
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '20700', 'NV::CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '21300', 'NV:HTTT,CNPM,KHMT:CS1');
    
-- h3) SINH VIEN HAI NGANH CNTT VA CNPM CO THE DOC THONG BAO CUA NHAU O CA HAI CO SO
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '12100', 'SV:CNPM,CNTT:CS1,CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '11100', 'SV:CNTT:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('P_THONGBAO', '11000', 'SV:CNPM:CS2');
    

END;

/
select * from dba_sa_levels;
select * from dba_sa_compartments;
select * from dba_sa_groups;
/
--select * from ALL_SA_LABELS;
/

BEGIN

    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME  => 'P_THONGBAO',
        SCHEMA_NAME  => 'ADM',
        TABLE_NAME  => 'THONGBAO',
        TABLE_OPTIONS  => 'LABEL_DEFAULT,READ_CONTROL'
    );
END;
/



TRUNCATE TABLE ADM.THONGBAO;
/

INSERT INTO ADM.THONGBAO  VALUES(1, 'tbao cho truong khoa tat ca bo mon hai cs:', CHAR_TO_LABEL('P_THONGBAO', 'TKH:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'));
INSERT INTO ADM.THONGBAO  VALUES(2, 'tbao cho truong cac bo mon o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1'));
INSERT INTO ADM.THONGBAO  VALUES(3, 'tbao cho truong cac bo mon o cs2:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS2'));
INSERT INTO ADM.THONGBAO  VALUES(4, 'tbao cho truong cac bo mon HTTT o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:HTTT:CS1,CS2'));
INSERT INTO ADM.THONGBAO  VALUES(5, 'tbao cho truong cac bo mon CNPM o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:CNPM:CS1,CS2'));
INSERT INTO ADM.THONGBAO  VALUES(6, 'tbao cho truong cac bo mon CNPM o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:CNPM:CS1'));
INSERT INTO ADM.THONGBAO  VALUES(7, 'tbao cho truong cac bo mon MMT o cs2:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:MMT:CS2'));
INSERT INTO ADM.THONGBAO  VALUES(8, 'tbao cho truong cac bo mon KHMT o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:KHMT:CS1'));


INSERT INTO ADM.THONGBAO  VALUES(9, 'tbao cho giao vu tat ca cac mon o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'));
INSERT INTO ADM.THONGBAO  VALUES(10, 'tbao cho giao vu mon KHMT,CNTT,TGMT o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'GVU:KHMT,CNTT,TGMT:CS1'));
INSERT INTO ADM.THONGBAO  VALUES(11, 'tbao cho giao vu mon TGMT o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'GVU:TGMT:CS1,CS2'));

INSERT INTO ADM.THONGBAO  VALUES(12, 'tbao cho truong cac bo mon o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'));

INSERT INTO ADM.THONGBAO  VALUES(13, 'tbao cho sinh vien mon HTTT o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'SV:HTTT:CS1'));


INSERT INTO ADM.THONGBAO  VALUES(14, 'tbao cho truong cac bo mon KHMT o hai cs:', CHAR_TO_LABEL('P_THONGBAO', 'TDV:KHMT:CS1,CS2'));


INSERT INTO ADM.THONGBAO  VALUES(15, 'tbao cho giang vien khong quan trong mon hoc o hai cs:', CHAR_TO_LABEL('P_THONGBAO', 'GV::CS1,CS2'));



INSERT INTO ADM.THONGBAO  VALUES(16, 'tbao cho nhan vien khong quan trong mon hoc o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'NV::CS1'));
INSERT INTO ADM.THONGBAO  VALUES(17, 'tbao cho nhan vien mon HTTT, CNPM, KHMT o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'NV:HTTT,CNPM,KHMT:CS1'));



INSERT INTO ADM.THONGBAO  VALUES(18, 'tbao cho sinh vien mon CNPM,CNTT o 2 cs:', CHAR_TO_LABEL('P_THONGBAO', 'SV:CNPM,CNTT:CS1,CS2'));

INSERT INTO ADM.THONGBAO  VALUES(19, 'tbao cho sinh vien mon CNTT o cs1:', CHAR_TO_LABEL('P_THONGBAO', 'SV:CNTT:CS1'));

INSERT INTO ADM.THONGBAO  VALUES(20, 'tbao cho sinh vien mon CNPM o cs2:', CHAR_TO_LABEL('P_THONGBAO', 'SV:CNPM:CS2'));

commit;


--a) 

BEGIN SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'P_THONGBAO',
        USER_NAME  => 'TKH005',
        MAX_READ_LABEL  => 'TKH:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'
); END;
/



-- b)
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6); DV INT; BM VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM ADM.NHANSU WHERE VAITRO = ''Truong don vi'' AND MACS = ''2''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'
            );
    END LOOP; CLOSE CUR; 

END;
/

--c)
BEGIN SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'P_THONGBAO',
        USER_NAME  => 'GVU000',
        MAX_READ_LABEL  => 'GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'
); END;
/

--d) T1: 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2' GIONG CAU B


-- e)--DROP POLICY BEN SINH VIEN DE ADMIN_OLS CO QUYEN LAY TAT CA SINH VIEN SAU DO CAI LAI
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MASV FROM ADM.SINHVIEN WHERE MANGANH = ''BMHTTT'' AND MACS = ''1''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'SV:HTTT:CS1'
        );
    END LOOP; CLOSE CUR;
END;
/

-- f)
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM ADM.NHANSU WHERE VAITRO = ''Truong don vi'' AND MADV = ''BMKHMT'' AND MACS = ''1''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'TDV:KHMT:CS1'
        );
    END LOOP; CLOSE CUR;
END;
/


--g) T4: TDV:KHMT:CS1,CS2 trung cac tdv cau f
/*
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM ADM.NHANSU WHERE VAITRO = ''Truong don vi'' AND MADV = ''BMKHMT''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'TDV:KHMT:CS1,CS2'
        );
    END LOOP; CLOSE CUR;
END;*/


--h1) CAC GIANG VIEN DOC DUOC HET THONG BAO CUA 2 CO SO KHONG QUAN TRONG BO MON
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM ADM.NHANSU WHERE VAITRO = ''Giang vien''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'GV::CS1,CS2'
        );
    END LOOP; CLOSE CUR;
END;
/

--h2) NHAN VIEN CO SO 1 DOC DUOC HET THONG BAO CUA CO SO MINH LAM VIEC KHONG QUAN TRONG BO MON
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM ADM.NHANSU WHERE VAITRO = ''Nhan vien co ban'' AND MACS = ''1''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'NV::CS1'
        );
    END LOOP; CLOSE CUR;
END;
/

--h3) SINH VIEN HAI NGANH CNTT VA CNPM CO THE DOC THONG BAO CUA NHAU O CA HAI CO SO
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MASV FROM ADM.SINHVIEN WHERE MANGANH = ''BMCNTT'' OR MANGANH = ''BMCNPM''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'SV:CNPM,CNTT:CS1,CS2'
        );
    END LOOP; CLOSE CUR;
END;
/
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MASV FROM ADM.SINHVIEN WHERE MANGANH = ''BMCNTT'' OR MANGANH = ''BMCNPM''';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'P_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'SV:CNPM,CNTT:CS1,CS2'
        );
    END LOOP; CLOSE CUR;
END;
/